review/Implemention of notification endpoint
yourtrading-ai/fishnet-cod pull request #5
Opened 2023-03-20 16:20 UTC by AneequeZubair9

As mentioned we  need to show the new, unapproved permission requests, grouped by datasets.

@MHHukiewitz 
Waiting for your review

2023-03-27 09:29 UTC, MHHukiewitz requested changes

2023-03-30 15:56 UTC, MHHukiewitz requested changes

2023-03-30 15:56 UTC, MHHukiewitz commented on src/fishnet_cod/api/test.py
> +    assert resp.status_code == 200
please make a more comprehensive test

2023-03-30 15:56 UTC, MHHukiewitz commented on src/fishnet_cod/api/main.py
> +    ]
I think it would make sense if you create an Index on `authorizer` and `status` and use it to query for both at the same time

2023-03-30 15:56 UTC, MHHukiewitz commented on src/fishnet_cod/api/main.py
> +    datasets_records = await asyncio.gather(*req)
You are fetching Permissions again, not Datasets

2023-03-30 15:56 UTC, MHHukiewitz commented on src/fishnet_cod/api/main.py
> +    ]
the items are not Notifications

2023-04-11 21:02 UTC, AneequeZubair9 reviewed
@MHHukiewitz 
Implemented the notification endpoint 
Tested some endpoints (still need some more to dos)
Fixed the List hashable issue

2023-05-12 16:51 UTC, merged